#!/usr/bin/env bash
# session-end.sh — Collect internal signals for self-improvement (SessionEnd)
# Reads audit logs for the current session, produces a session summary,
# and appends signals for the evolve pattern detector.
set -uo pipefail

# Scope gate
SCOPE_LIB="$(dirname "$0")/_scope.sh"
if [ -f "$SCOPE_LIB" ]; then
  # shellcheck disable=SC1090
  . "$SCOPE_LIB" && harness_in_scope || exit 0
fi

INPUT=$(cat 2>/dev/null || echo "{}")
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty' 2>/dev/null)
CWD=$(pwd)

[ -z "$SESSION_ID" ] && exit 0

LOG_FILE="${HOME}/.claude/audit-logs/$(date +%Y-%m-%d).jsonl"
[ ! -f "$LOG_FILE" ] && exit 0

# ─── Session summary ─────────────────────────────────────
STATE_DIR=".claude/state"
mkdir -p "$STATE_DIR"
SUMMARY="${STATE_DIR}/session-summary.md"

ENTRIES=$(jq -c --arg sid "$SESSION_ID" --arg cwd "$CWD" \
  'select(.session == $sid and .cwd == $cwd)' "$LOG_FILE" 2>/dev/null || echo "")

[ -z "$ENTRIES" ] && exit 0

EDIT_COUNT=$(echo "$ENTRIES" | jq -s 'map(select(.tool=="Edit" or .tool=="Write")) | length')
BASH_COUNT=$(echo "$ENTRIES" | jq -s 'map(select(.tool=="Bash")) | length')
TOP_FILES=$(echo "$ENTRIES" | jq -r 'select(.file) | .file' | sort | uniq -c | sort -rn | head -5 | sed 's/^/  - /')

TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "N/A")

cat > "$SUMMARY" <<EOF
# Session Summary

- Timestamp: ${TS}
- Session: ${SESSION_ID}
- Branch: ${BRANCH}
- Edits: ${EDIT_COUNT}
- Bash calls: ${BASH_COUNT}

## Top edited files
${TOP_FILES:-  (none)}

> Generated by session-end.sh. Feeds evolve for harness improvement proposals.
EOF

# ─── Append signals for evolve ────────────────────────────
SIGNALS_FILE="${HARNESS_ROOT:-$(dirname "$0")/..}/watchlist/state/signals.jsonl"
SIGNALS_DIR=$(dirname "$SIGNALS_FILE")
mkdir -p "$SIGNALS_DIR" 2>/dev/null || true

# Signal: which commands/hooks were used this session
COMMANDS_USED=$(echo "$ENTRIES" | jq -r 'select(.tool=="Skill") | .command // empty' | sort -u | jq -Rsc 'split("\n") | map(select(. != ""))')

# Signal: error patterns
ERROR_PATTERNS=$(echo "$ENTRIES" | jq -s '
  map(select(.result == "error")) |
  group_by(.tool) |
  map({tool: .[0].tool, count: length}) |
  sort_by(-.count) |
  .[0:5]
' 2>/dev/null || echo "[]")

# Write signal line
jq -nc \
  --arg ts "$TS" \
  --arg sid "$SESSION_ID" \
  --arg project "$(basename "$CWD")" \
  --arg branch "$BRANCH" \
  --argjson edits "$EDIT_COUNT" \
  --argjson bash_calls "$BASH_COUNT" \
  --argjson commands "$COMMANDS_USED" \
  --argjson errors "$ERROR_PATTERNS" \
  '{
    timestamp: $ts,
    session: $sid,
    project: $project,
    branch: $branch,
    edits: $edits,
    bash_calls: $bash_calls,
    commands_used: $commands,
    error_patterns: $errors,
    type: "session_end"
  }' >> "$SIGNALS_FILE" 2>/dev/null || true

echo "[harness] Session summary: ${SUMMARY}"
exit 0
