#!/usr/bin/env bash
# snapshot-diff.sh — Compare new snapshot with previous and generate proposal if changed
#
# Usage:
#   ./scripts/snapshot-diff.sh <source-id> <new-snapshot-file>
#
# Reads the previous snapshot from watchlist/snapshots/{id}.latest.md,
# compares with the new one, and if significant changes detected,
# generates a proposal in watchlist/proposals/.
set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "$0")/.." && pwd -P)"
SNAPSHOTS="${HARNESS_DIR}/watchlist/snapshots"
PROPOSALS="${HARNESS_DIR}/watchlist/proposals"
WATCHLIST="${HARNESS_DIR}/watchlist/watchlist.yaml"

SOURCE_ID="${1:-}"
NEW_SNAPSHOT="${2:-}"

if [ -z "$SOURCE_ID" ] || [ -z "$NEW_SNAPSHOT" ] || [ ! -f "$NEW_SNAPSHOT" ]; then
  echo "Usage: snapshot-diff.sh <source-id> <new-snapshot-file>"
  exit 1
fi

PREV_SNAPSHOT="${SNAPSHOTS}/${SOURCE_ID}.latest.md"
TODAY=$(date +%Y-%m-%d)

mkdir -p "$SNAPSHOTS" "$PROPOSALS"

# ── No previous snapshot → save as baseline ───────────────
if [ ! -f "$PREV_SNAPSHOT" ]; then
  cp "$NEW_SNAPSHOT" "$PREV_SNAPSHOT"
  echo "Baseline snapshot saved: ${PREV_SNAPSHOT}"
  echo "No previous snapshot to compare — skipping proposal generation."

  # Log
  echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"source\":\"${SOURCE_ID}\",\"action\":\"baseline\",\"file\":\"${PREV_SNAPSHOT}\"}" \
    >> "${HARNESS_DIR}/watchlist/state/watch-log.jsonl" 2>/dev/null || true
  exit 0
fi

# ── Diff ──────────────────────────────────────────────────
DIFF_OUTPUT=$(diff -u "$PREV_SNAPSHOT" "$NEW_SNAPSHOT" 2>/dev/null || true)

if [ -z "$DIFF_OUTPUT" ]; then
  echo "No changes detected for ${SOURCE_ID}."

  echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"source\":\"${SOURCE_ID}\",\"action\":\"no_change\"}" \
    >> "${HARNESS_DIR}/watchlist/state/watch-log.jsonl" 2>/dev/null || true
  exit 0
fi

# ── Changes detected → get metadata from watchlist.yaml ───
SOURCE_NAME="$SOURCE_ID"
AFFECTS="[]"
FOCUS="[]"

if command -v python3 >/dev/null 2>&1; then
  eval "$(python3 -c "
import yaml
with open('$WATCHLIST') as f:
    data = yaml.safe_load(f)
for src in data.get('sources', []):
    if src['id'] == '$SOURCE_ID':
        print(f'SOURCE_NAME=\"{src.get(\"name\", \"$SOURCE_ID\")}\"')
        affects = ', '.join(src.get('affects', []))
        focus = ', '.join(src.get('focus', []))
        print(f'AFFECTS=\"{affects}\"')
        print(f'FOCUS=\"{focus}\"')
        break
" 2>/dev/null)" || true
fi

# ── Generate proposal ─────────────────────────────────────
PROPOSAL_ID="${TODAY}-${SOURCE_ID}"
PROPOSAL_FILE="${PROPOSALS}/${PROPOSAL_ID}.md"

cat > "$PROPOSAL_FILE" <<EOF
---
id: ${PROPOSAL_ID}
source_id: ${SOURCE_ID}
source_name: ${SOURCE_NAME}
created_at: ${TODAY}
status: pending
---

# Proposal: ${SOURCE_NAME} — Changes Detected

## What Changed

Changes were detected in **${SOURCE_NAME}** since last check.

### Diff

\`\`\`diff
${DIFF_OUTPUT}
\`\`\`

## Focus Areas

${FOCUS}

## Affected Harness Files

${AFFECTS}

## Recommended Actions

<!-- Claude should fill this section after analyzing the diff -->
1. Review the diff above
2. Determine if harness templates/hooks need updating
3. If yes, draft the specific file changes needed
4. Estimate impact on registered projects

## Decision

- [ ] **Apply** — implement the recommended changes
- [ ] **Later** — revisit in the next cycle
- [ ] **Dismiss** — not relevant, no action needed

> Generated by snapshot-diff.sh on ${TODAY}
EOF

# Update the stored snapshot
cp "$NEW_SNAPSHOT" "$PREV_SNAPSHOT"

# Log
echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"source\":\"${SOURCE_ID}\",\"action\":\"proposal_created\",\"proposal\":\"${PROPOSAL_ID}\"}" \
  >> "${HARNESS_DIR}/watchlist/state/watch-log.jsonl" 2>/dev/null || true

echo "Changes detected! Proposal created: ${PROPOSAL_FILE}"
echo "Review with: cat ${PROPOSAL_FILE}"
